# -*- coding: utf-8 -*-
"""Day-07-2D-Gradient-Descent.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnGB4PrWFonBJd1SSgEVl2epD1czLnp9
"""

import numpy as np
import matplotlib.pyplot as plt

def loss(w1,w2):
  return w1**2 + w2**2

def gradient(w1,w2):
  dw1 = 2*w1
  dw2 = 2*w2
  return dw1,dw2

lr = 0.1
w1 = 8
w2 = 6
values = []

for i in range(50):
  dw1, dw2 = gradient(w1,w2)
  w1 = w1 - lr*dw1
  w2 = w2 - lr*dw2
  values.append((w1,w2))

print("Final w1:",w1)
print("Final w2:",w2)
print("Final loss:",loss(w1,w2))

values = np.array(values)

w1_values = np.linspace(-10, 10, 200)
w2_values = np.linspace(-10, 10, 200)

W1, W2 = np.meshgrid(w1_values, w2_values)

Z = loss(W1, W2)

plt.figure(figsize=(8, 6))

plt.contour(W1, W2, Z, levels=30)

plt.plot(
    values[:, 0],
    values[:, 1],
    marker="o"
)

plt.xlabel("w1")
plt.ylabel("w2")
plt.title("Gradient Descent Path")

plt.show()

