# -*- coding: utf-8 -*-
"""Day-24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9KlBdkgYlMfsY2PHbIBtoon-wWKCr7g
"""

import numpy as np
from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

data = np.array([
    [2, 3], [3, 3], [2.5, 4],      # tight little group A
    [8, 8], [9, 8], [8.5, 9],      # tight little group B
    [15, 3], [16, 2.5]             # tight little group C
])
labels = [f'cust_{i}' for i in range(len(data))]

Z = linkage(data, method='ward')
print(Z.round(2))

dendrogram(Z, labels=labels)
plt.title('Dendrogram - Agglomerative Clustering (Ward linkage)')
plt.ylabel('Distance at merge')

plt.show()

import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons

X, _ = make_moons(n_samples=200, noise=0.07, random_state=42)



rng = np.random.RandomState(3)
noise_points = rng.uniform(low=-2, high=3, size=(10, 2))
X_full = np.vstack([X, noise_points])

model = DBSCAN(eps=0.2, min_samples=5)
labels = model.fit_predict(X_full)

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_noise = list(labels).count(-1)
print("Number of clusters found:", n_clusters)
print("Number of noise points found:", n_noise)