# -*- coding: utf-8 -*-
"""Day-22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0w2yhEIyq4NmeI0VTX4ZXNDRmDHkwsX
"""

import pandas as pd
from sklearn.datasets import load_iris
from scipy.spatial.distance import pdist, squareform

iris = load_iris()
X = pd.DataFrame(iris.data,
                  columns=['sepal_length','sepal_width','petal_length','petal_width'])

# Take just the first 5 flowers so the table stays readable
small = X.iloc[:5]

distances = squareform(pdist(small, metric='euclidean'))
dist_df = pd.DataFrame(distances,
                        index=[f'flower_{i}' for i in range(5)],
                        columns=[f'flower_{i}' for i in range(5)])
print(dist_df.round(2))

print(X.corr().round(2))
print(X.describe().round(2))

