# -*- coding: utf-8 -*-
"""Day-20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15gOvbUX2LOTdko3x-ewx1cACI6zPZwtI
"""

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_text = vectorizer.fit_transform(texts)

from sklearn.svm import SVC
model = SVC(kernel='rbf')
model.fit(X, y)