# -*- coding: utf-8 -*-
"""Day-17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HM4akJyxwIGz4H_JjooiIDI3V6xpfKXt
"""

import numpy as np

def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2)**2))

def knn_predict(X_train, y_train, query_point, k=3):
    distances = []
    for i in range(len(X_train)):
        dist = euclidean_distance(X_train[i], query_point)
        distances.append((dist, y_train[i]))

    distances.sort(key=lambda x: x[0])
    k_nearest_labels = [label for _, label in distances[:k]]

    values, counts = np.unique(k_nearest_labels, return_counts=True)
    prediction = values[np.argmax(counts)]
    return prediction

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)