# -*- coding: utf-8 -*-
"""Day-15-Practice-Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IR6gSLHvTi5dKpDQ75x0EnJDsSwtiscx
"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

y_true = [1, 0, 1, 1, 0, 1, 0, 0]   # 1 = churned, 0 = stayed
y_pred = [1, 0, 0, 1, 0, 1, 1, 0]   # what the model guessed

cm = confusion_matrix(y_true, y_pred)
print(cm)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted: No', 'Predicted: Yes'],
            yticklabels=['Actual: No', 'Actual: Yes'])
plt.xlabel('Predicted Label')
plt.ylabel('Actual Label')
plt.title('Confusion Matrix')
plt.show()

