# -*- coding: utf-8 -*-
"""Day-13-Model-Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOT99GYABhB0vr9HP1rBV7_P9OhqhOX_
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import (LinearRegression, Ridge, Lasso, ElasticNet)
from sklearn.metrics import (r2_score, mean_squared_error, mean_absolute_error)
from sklearn.pipeline import make_pipeline, Pipeline

from os import X_OK
from sklearn.datasets import load_diabetes

data = load_diabetes()

X = pd.DataFrame(data.data, columns=data.feature_names)
y= pd.Series(data.target, name = "target")

X.head()

y.head()

X.shape,y.shape

X.isnull().sum()

y.isnull().sum()

print(np.isinf(X_train).sum().sum())

pd.get_dummies(X)

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

models = {
    "Linear Regression": LinearRegression(),

    "Ridge": Ridge(alpha=1.0),

    "Lasso": Lasso(alpha=0.1),

    "ElasticNet": ElasticNet(
        alpha=0.1,
        l1_ratio=0.5
    )
}

results = []

for name, model in models.items():

    pipeline = make_pipeline(
        StandardScaler(),
        model
    )

    scores = cross_val_score(
        pipeline,
        X_train,
        y_train,
        cv=5,
        scoring="r2"
    )

    results.append({
        "Model": name,
        "Mean CV R2": scores.mean(),
        "Std CV R2": scores.std()
    })

results_df = pd.DataFrame(results)

print(results_df)

