# -*- coding: utf-8 -*-
"""Day-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZN-Wa-2NI0BvfCuA6U_41cFgLZRC07u8
"""

import time
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, f1_score

data = load_breast_cancer()
X, y = data.data, data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

ada = AdaBoostClassifier(n_estimators=100, random_state=42)
ada.fit(X_train, y_train)
ada_pred = ada.predict(X_test)

gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb.fit(X_train, y_train)
gb_pred = gb.predict(X_test)

print("AdaBoost:", accuracy_score(y_test, ada_pred), f1_score(y_test, ada_pred))
print("Gradient Boosting:", accuracy_score(y_test, gb_pred), f1_score(y_test, gb_pred))

import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score

start = time.time()
xgb_model = xgb.XGBClassifier(n_estimators=100, random_state=42, eval_metric='logloss')
xgb_model.fit(X_train, y_train)
xgb_time = time.time() - start
xgb_pred = xgb_model.predict(X_test)

print(f"XGBoost: Accuracy={accuracy_score(y_test, xgb_pred):.4f}, F1={f1_score(y_test, xgb_pred):.4f}, Time={xgb_time:.4f}s")

from sklearn.model_selection import cross_val_score, KFold
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import time

cv = KFold(n_splits=5, shuffle=True, random_state=42)

models = {
    'Random Forest (Bagging)': RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1),
    'XGBoost (Boosting)': xgb.XGBClassifier(n_estimators=300, random_state=42, eval_metric='logloss', n_jobs=-1)
}

for name, model in models.items():
    start = time.time()
    scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy')
    elapsed = time.time() - start
    print(f"{name}: Mean Accuracy={scores.mean():.4f} (+/- {scores.std():.4f}), Total Time={elapsed:.3f}s")

