# -*- coding: utf-8 -*-
"""Day-08-Regression-Fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXH6hR0AXs0vOvPjubWmDYI9fGzuWRZb
"""

x = 2
w = 12
b = 30

prediction = b + w * x

print("Prediction:", prediction)

"""#Part 2 — Simple Linear Regression"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([35, 40, 50, 55, 65, 70])

"""x = Hours studied ;
y = Actual marks
"""

m = 7
c = 28

y_pred = m*x + c
print(y_pred)

residual = y - y_pred
print(residual)

mse = 1/len(y) * (residual**2).sum()
print("MSE: ",mse)

plt.scatter(x,y)
plt.plot(x,y_pred,color = 'green')

plt.xlabel("Hours studied")
plt.ylabel("Exam Marks")
plt.title("Simple Linear Regression")

plt.show()

"""# Part 3"""

w1 = 7
b1 = 28

w2 = 5
b2 = 20

pred1 = b1 + w1 * x
pred2 = b2 + w2 * x

mse1 = np.mean((y - pred1) ** 2)
mse2 = np.mean((y - pred2) ** 2)

print("Model 1 MSE:", mse1)
print("Model 2 MSE:", mse2)

plt.scatter(x, y)

plt.plot(x, pred1, label="Model 1")
plt.plot(x, pred2, label="Model 2")

plt.xlabel("Hours Studied")
plt.ylabel("Exam Marks")
plt.legend()

plt.show()

residuals = y - y_pred

print("Actual:", y)
print("Predicted:", y_pred)
print("Residuals:", residuals)

plt.scatter(y_pred, residuals)

plt.axhline(y=0, linestyle="--")

plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot")

plt.show()

plt.scatter(y, residuals)

plt.axhline(y=0, linestyle="--")

plt.xlabel("Actual Target Values")
plt.ylabel("Residuals")
plt.title("Residuals vs Actual Target")

plt.show()

plt.hist(residuals, bins=10)

plt.xlabel("Residual")
plt.ylabel("Frequency")
plt.title("Residual Distribution")

plt.show()

n