# -*- coding: utf-8 -*-
"""Day-8-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Y20jNK2IQEQsHOH99GWYl51zIJHp1cq
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# -------------------------
# 1. Dataset
# -------------------------

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=float)

y = np.array([
    35, 41, 49, 55, 64,
    70, 76, 84, 91, 97
], dtype=float)

# -------------------------
# 2. Convert to 2D feature matrix
# -------------------------

X = x.reshape(-1, 1)

# -------------------------
# 3. Train/Test Split
# -------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# -------------------------
# 4. Create Model
# -------------------------

model = LinearRegression()

# -------------------------
# 5. Train
# -------------------------

model.fit(X_train, y_train)

# -------------------------
# 6. Predict
# -------------------------

y_pred = model.predict(X_test)

# -------------------------
# 7. Evaluation
# -------------------------

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("Coefficient:", model.coef_[0])
print("Intercept:", model.intercept_)

print("\nEvaluation")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

# -------------------------
# 8. Residuals
# -------------------------

residuals = y_test - y_pred

results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred,
    "Residual": residuals
})

print("\nPrediction Results")
print(results)

# -------------------------
# 9. Actual vs Predicted
# -------------------------

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")

plt.title("Actual vs Predicted")

plt.show()

# -------------------------
# 10. Residual Plot
# -------------------------

plt.scatter(y_pred, residuals)

plt.axhline(0, linestyle="--")

plt.xlabel("Predicted Values")
plt.ylabel("Residuals")

plt.title("Residuals vs Predicted")

plt.show()

# -------------------------
# 11. Residual Distribution
# -------------------------

plt.hist(residuals, bins=5)

plt.xlabel("Residual")
plt.ylabel("Frequency")

plt.title("Residual Distribution")

plt.show()

