# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1419GJsHlGRAKzlme94OGNe8RfOeMo2jy
"""

import numpy as np
import pandas as pd

df = pd.read_csv('customers.csv')
X = df.values

def kmeans_from_scratch(X, k, max_iters=100, random_state=42):
    np.random.seed(random_state)
    n_samples = X.shape[0]

    # Step 1: randomly pick k data points as initial centroids
    random_idx = np.random.choice(n_samples, k, replace=False)
    centroids = X[random_idx]

    for iteration in range(max_iters):
        # Step 2: assign each point to its nearest centroid
        distances = np.zeros((n_samples, k))
        for cluster_idx in range(k):
            distances[:, cluster_idx] = np.linalg.norm(X - centroids[cluster_idx], axis=1)
        labels = np.argmin(distances, axis=1)

        # Step 3: recompute centroids as the mean of assigned points
        new_centroids = np.zeros((k, X.shape[1]))
        for cluster_idx in range(k):
            points_in_cluster = X[labels == cluster_idx]
            if len(points_in_cluster) > 0:
                new_centroids[cluster_idx] = points_in_cluster.mean(axis=0)
            else:
                new_centroids[cluster_idx] = centroids[cluster_idx]

        # Step 4: stop when centroids no longer move (convergence)
        if np.allclose(centroids, new_centroids, atol=1e-6):
            print(f"Converged after {iteration+1} iterations")
            break
        centroids = new_centroids

    return labels, centroids

labels, centroids = kmeans_from_scratch(X, k=3)
print(centroids.round(2))
print("Cluster sizes:", np.bincount(labels))

import numpy as np
import pandas as pd

df = pd.read_csv('customers.csv')
X = df.values

def kmeans_from_scratch(X, k, max_iters=100, random_state=42):
    np.random.seed(random_state)
    n_samples = X.shape[0]

    # Step 1: randomly pick k data points as initial centroids
    random_idx = np.random.choice(n_samples, k, replace=False)
    centroids = X[random_idx]

    for iteration in range(max_iters):
        # Step 2: assign each point to its nearest centroid
        distances = np.zeros((n_samples, k))
        for cluster_idx in range(k):
            distances[:, cluster_idx] = np.linalg.norm(X - centroids[cluster_idx], axis=1)
        labels = np.argmin(distances, axis=1)

        # Step 3: recompute centroids as the mean of assigned points
        new_centroids = np.zeros((k, X.shape[1]))
        for cluster_idx in range(k):
            points_in_cluster = X[labels == cluster_idx]
            if len(points_in_cluster) > 0:
                new_centroids[cluster_idx] = points_in_cluster.mean(axis=0)
            else:
                new_centroids[cluster_idx] = centroids[cluster_idx]

        # Step 4: stop when centroids no longer move (convergence)
        if np.allclose(centroids, new_centroids, atol=1e-6):
            print(f"Converged after {iteration+1} iterations")
            break
        centroids = new_centroids

    return labels, centroids

labels, centroids = kmeans_from_scratch(X, k=3)
print(centroids.round(2))
print("Cluster sizes:", np.bincount(labels))

from sklearn.cluster import KMeans
model = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
model.fit(X)

from sklearn.cluster import KMeans

model = KMeans(n_clusters=3, init='k-means++', n_init=10, random_state=42)
model.fit(X)

print(model.cluster_centers_.round(2))
print("Inertia (WCSS):", round(model.inertia_, 2))

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

k_values = range(2, 9)
inertias = []
silhouette_scores = []

for k in k_values:
    model = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    labels = model.fit_predict(X)
    inertias.append(model.inertia_)
    silhouette_scores.append(silhouette_score(X, labels))

fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].plot(list(k_values), inertias, marker='o')
axes[0].set_title('Elbow Method')
axes[1].plot(list(k_values), silhouette_scores, marker='o')
axes[1].set_title('Silhouette Score by K')
plt.show()

